### ISSUE TITLE
Transparent drawing

### ISSUE THREAD

**Issue by Danik** [Danik/Pyxel-Edit#32]
Ability to draw with alpha blending. This can work in two modes; adding each stroke with a single consistent transparency onto the layer, or adding color continuously throughout the stroke as long as the mouse button is held down. (the way opacity and flow works in Photoshop for example)

**Comment by Danik** [comment]
Implemented.

**Comment by sebovzeoueb** [comment]
Hey, is this still implemented? I would like to do the single consistent transparency thing and I can't figure out how to do it.

EDIT: on closer reading, I think I'm misunderstanding the feature. What I'm looking for is a mode where the pixels are replaced instead of blended with the existing ones. Is that implemented, or would you consider doing it?

**Comment by mikotalik** [comment]
I would also be interested in alpha without blending, replacing the pixel color value
